name: Update Focus Charts

on:
  schedule:
    - cron: '0 12 * * 6' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib python-bcb

      - name: Preparar ambiente
        run: |
          mkdir -p data
          # O config.json aponta para a raiz onde as funções buscarão /data/
          echo "{
            \"caminho_rede\": \"$GITHUB_WORKSPACE\"
          }" > settings/config.json

      - name: Executar script
        run: python main.py

      - name: Limpeza e Commit
        if: always()
        run: |
          # Remove configurações e dados brutos
          rm -f settings/config.json
          rm -rf data
          
          # Configura Git para commit
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add charts/*.png
          git commit -m "Autodeploy: Atualização Focus $(date +'%Y-%m-%d')" || exit 0
          git push