name: Update Focus Charts

on:
  schedule:
    - cron: '0 12 * * 6' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib python-bcb plotly

      - name: Preparar ambiente
        run: |
          mkdir -p data
          echo "{
            \"caminho_rede\": \"$GITHUB_WORKSPACE\"
          }" > settings/config.json

      - name: Executar script principal
        run: python main.py

      - name: Commit dos gráficos estáticos (PNG) na branch principal
        run: |
          rm -f settings/config.json
          rm -rf data
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add charts/*.png
          git commit -m "Autodeploy: Atualização PNGs Focus $(date +'%Y-%m-%d')" || true
          git push

      - name: Preparar arquivos para o Dashboard Interativo
        run: |
          mkdir -p public/charts/interativo
          cp index.html public/
          cp charts/interativo/*.html public/charts/interativo/

      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false